### ISSUE TITLE
제안: index.html 전체 큰틀 작성

### ISSUE THREAD

**Issue by hoheesu** [gitproject-team1/team1_git#1]
## 설명

index.html의 기본 구조를 완성하고, css/style.css 파일 생성후 연결

## 할일

- [x] set doctype
- [x] html, head, body
- [x] meta, title
- [x] link, script
- [x] .container

## 참조

[google](google.co.kr)

**Comment by ghgt1** [comment]
좋습니다! 언능 시작해주세요!

**Comment by ulgoon** [comment]
Set assignees and label plz
