### ISSUE TITLE
제안) 상단 박스부분

### ISSUE THREAD

**Issue by 1myeji** [gitproject-team1/team1_git#4]
## 설명

상단 박스 부분을 완성하겠음

## 할일

- [x] h1
- [x] p
- [x] button
- [x] image

## 참조

-[google](https://www.google.com)

**Comment by ulgoon** [comment]
To use markdown properly, locate delimiter between signs and text
Set assignees and labels plz

**Comment by ghgt1** [comment]
예지님 마크다운수정해주시고 시작해주세요!
