### ISSUE TITLE
제안: index.html-header 작성

### ISSUE THREAD

**Issue by sdh11987** [gitproject-team1/team1_git#5]
## 설명

기본틀 index.html에서 header 영역 완성

## 할일

- [x] header영역 완성

## 참조

-[google](<https://www.google.com/>)
-[피보나치킨](<https://fibonachicken.herokuapp.com/>)

**Comment by ghgt1** [comment]
동현님 html 구조 작업 마무리되면 시작해주시면 될거같습니다!
